name: micpy
channels:
  - conda-forge
dependencies:
  - scikit-image
  - scipy
  - numpy
  - pandas
  - pip
  - microfilm
  - matplotlib
  - napari
  - pip:
    - jupyterlab
    - jupyterlab-spellchecker
    - aicsimageio
    - readlif
    - aicspylibczi
    - seaborn
    - napari-segment-blobs-and-things-with-membranes